"""Feedback-loop stress test: what happens to the model and the no-model orderings if the County
inspected only what a model flagged, round after round?

The labels, and the RECORD every feature is built from, are generated by the inspections that
are made. If a routine inspection is skipped, its label is missing AND the facility's history goes
stale: no new score, no "days since", no majors. An earlier version of this script dropped only the
labels and kept every facility's full record, and it selected purely on model features, so it
could not show this harm (and called the rule and persistence untouchable, which they are not:
they read the same record).

Here, in each quarter of 2024:
  1. a model is trained on the (censored) record so far;
  2. the quarter's routine inspections are kept only if flagged in its top KEEP share (arm B), or
     that plus a random BASELINE share of the rest (arm C); arm A keeps everything;
  3. every other routine inspection is deleted from the record, with the facility's non-routine
     visits in the FOLLOWUP_DAYS after it (the re-inspections it would have triggered).
Then the model, the one-line rule and persistence are rebuilt from the censored record and scored
on the real 2025+ inspections (whose labels are all observed), with recall broken out by ZIP
income group. Arm C runs over several seeds.

Scope: this simulates an INSPECT-LESS policy, which this project does not propose. Reordering
visits within the County's schedule removes none, so it is arm A by construction."""
import json, os
import numpy as np, pandas as pd
from sklearn.metrics import roc_auc_score
import model_food as mf
from fairness_check import zip_groups

ROUNDS = [("2024-01-01", "2024-03-31"), ("2024-04-01", "2024-06-30"),
          ("2024-07-01", "2024-09-30"), ("2024-10-01", "2024-12-31")]
KEEP, BASELINE, FOLLOWUP_DAYS, SEEDS = 0.40, 0.15, 45, (0, 1, 2)
GROUPS = ["Q1 low", "Q2", "Q3", "Q4 high"]


def censor(raw, drop_rows):
    """Remove the routine inspections at `drop_rows` (index labels of `raw`) and each facility's
    non-routine visits in the FOLLOWUP_DAYS after one of them."""
    dropped = raw.loc[drop_rows, ["business_id", "completed_date"]]
    keep = pd.Series(True, index=raw.index)
    keep[drop_rows] = False
    nr = raw[raw["insp_type"].astype(str) != "Routine"].reset_index().rename(columns={"index": "_ix"})
    m = nr.merge(dropped.rename(columns={"completed_date": "_d"}), on="business_id")
    gap = (m["completed_date"] - m["_d"]).dt.days
    keep[m.loc[(gap >= 0) & (gap <= FOLLOWUP_DAYS), "_ix"].unique()] = False
    return raw[keep]


def simulate(raw, keep_share, base_share, seed):
    rng = np.random.default_rng(seed)
    rec = raw
    dropped = 0
    for start, end in ROUNDS if keep_share is not None else []:
        s, e = pd.Timestamp(start), pd.Timestamp(end)
        d = mf.routine_rows(mf.add_features(rec))
        tr = d[d["completed_date"] < s]
        cand = d[(d["completed_date"] >= s) & (d["completed_date"] <= e)]
        p = mf.Model(mf.HEADLINE).fit(tr).predict(cand)
        keep = p >= np.quantile(p, 1 - keep_share)
        rest = np.flatnonzero(~keep)
        if base_share and len(rest):
            keep[rng.choice(rest, int(round(base_share * len(rest))), replace=False)] = True
        drop = cand.index[~keep]
        dropped += len(drop)
        rec = censor(rec, drop)
    d = mf.routine_rows(mf.add_features(rec))
    te = (d["completed_date"] > pd.Timestamp(mf.TRAIN_END)).to_numpy()
    model = mf.Model(mf.HEADLINE).fit(d[mf.train_mask(d, mf.HEADLINE)])
    return d[te], {"Model": model.predict(d[te]), "One-line rule": d.loc[te, mf.BASELINES[mf.RULE]].values,
                   "Persistence": d.loc[te, "persistence"].values}, dropped


def main():
    raw = mf.load()
    inc = json.load(open("acs_cache.json")).get("inc", {}) if os.path.exists("acs_cache.json") else {}
    arms = {"A no censoring (= reordering only)": (None, 0.0, (0,)),
            f"B inspect only the model's top {KEEP:.0%}": (KEEP, 0.0, (0,)),
            f"C top {KEEP:.0%} + random {BASELINE:.0%} of the rest": (KEEP, BASELINE, SEEDS)}
    out = {}
    print(f"four quarterly rounds in 2024; unkept routine inspections and their follow-ups within "
          f"{FOLLOWUP_DAYS} days are deleted from the record; everything is rebuilt from what is left\n")
    for name, (ks, bs, seeds) in arms.items():
        runs = []
        for sd in seeds:
            t, scores, dropped = simulate(raw, ks, bs, sd)
            y = t["major"].values.astype(int)
            t = t.assign(zip5=t["zip"].astype(str).str.extract(r"(\d{5})")[0])
            t["income"] = t["zip5"].map(inc)
            grp = zip_groups(t, "income", GROUPS) if t["income"].notna().any() else pd.Series(np.nan, index=t.index)
            r = {"seed": sd, "dropped_routine": int(dropped),
                 "stale_days_since_last": round(float(t["days_since_last"].mean()), 1)}
            for a, v in scores.items():
                flag = mf.top_weights(v)
                r[a] = {"auc": round(float(roc_auc_score(y, v)), 4),
                        **{g: round(float(100 * (flag * y)[grp.values == g].sum() / max(y[grp.values == g].sum(), 1)), 1)
                           for g in GROUPS}}
            runs.append(r)
        agg = {a: {k: round(float(np.mean([r[a][k] for r in runs])), 3 if k == "auc" else 1)
                   for k in ["auc"] + GROUPS} for a in ("Model", "One-line rule", "Persistence")}
        out[name] = {"runs": runs, "mean": agg, "dropped_routine": runs[0]["dropped_routine"]}
        print(f"{name}: {runs[0]['dropped_routine']:,} routine inspections removed; mean days since the last visit "
              f"in 2025+ {runs[0]['stale_days_since_last']:.0f}")
        for a, m in agg.items():
            print(f"    {a:14s} AUC {m['auc']:.3f}   recall of majors (top 20%) by income quartile: " +
                  "  ".join(f"{g.split()[0]} {m[g]:.0f}%" for g in GROUPS))
    print("\nRead: B's losses against A are what inspecting only the model's picks would cost, for the model AND for")
    print("the rules that read the same record; C shows how much a random baseline gives back. Reordering visits")
    print("within the schedule removes none (arm A). Recall by group still has to be monitored live.")
    mf.save_results("feedback", {"rounds": ROUNDS, "keep": KEEP, "baseline": BASELINE,
                                 "followup_days": FOLLOWUP_DAYS, "arms": out})


if __name__ == "__main__":
    main()
