"""Feedback-loop stress test. The labels this model learns from are GENERATED by the
inspections it allocates: if you only inspect what a prior model flagged, you only get labels
there, the places you stop visiting look artificially clean, and the model can go blind to them,
worst in areas where it already has weak signal.

This tests the README/FAIRNESS mitigation ("keep a baseline of routine inspections everywhere")
instead of just asserting it. Three training regimes for the research model
(model_food.HEADLINE), all tested on the SAME held-out 2025+ set, recall broken out by ZIP income
quartile:

  A  representative  -- train on ALL routine <= 2024             (the ideal)
  B  pure targeting  -- 2023, plus only the 2024 rows a 2023 model flagged top-40% (censored labels)
  C  targeting+base  -- B's rows PLUS a random 15% baseline of the rest (the mitigation)

If B collapses low-income recall and C restores it, the mitigation is doing real work. The
one-line rule (model_food.RULE) and persistence are printed as reference rows: they are not
trained, so this censoring cannot touch them in one round."""
import pandas as pd, numpy as np, json, os
from sklearn.metrics import roc_auc_score
import model_food as mf


def main():
    df = mf.add_features(mf.load())
    d = mf.routine_rows(df).reset_index(drop=True)
    d["zip5"] = d["zip"].astype(str).str.extract(r"(\d{5})")[0]
    y = d["major"].values.astype(int)
    date = d["completed_date"]

    def fit_predict(tr_idx, te_mask):
        return mf.Model(mf.HEADLINE).fit(d.iloc[tr_idx]).predict(d[te_mask])

    pre = (date <= "2024-12-31").to_numpy()
    te = (date > "2024-12-31").to_numpy()
    y2023 = (date <= "2023-12-31").to_numpy()
    in2024 = ((date > "2023-12-31") & (date <= "2024-12-31")).to_numpy()

    # selection model: what a 2023-trained model would have flagged in 2024 (the "who gets inspected")
    sel_p = pd.Series(np.nan, index=d.index); sel_p[in2024] = fit_predict(np.where(y2023)[0], in2024)
    thr = np.nanquantile(sel_p[in2024], 0.60)                     # "inspect" the top 40% of 2024
    rng = np.random.default_rng(0)
    flagged_2024 = np.where(in2024 & (sel_p >= thr).values)[0]    # censored: only these 2024 labels survive
    dropped_2024 = np.where(in2024 & (sel_p < thr).values)[0]
    baseline = rng.choice(dropped_2024, int(0.15*len(dropped_2024)), replace=False)  # 15% random rescue
    arms = {"A representative (all <=2024)": np.where(pre)[0],
            "B pure targeting (censored)": np.concatenate([np.where(y2023)[0], flagged_2024]),
            "C targeting + 15% baseline": np.concatenate([np.where(y2023)[0], flagged_2024, baseline])}

    inc = json.load(open("acs_cache.json")).get("inc", {}) if os.path.exists("acs_cache.json") else {}
    tt = d[te].copy(); tt["income"] = tt["zip5"].map(inc)
    q = pd.qcut(tt["income"], 4, labels=["Q1 low", "Q2", "Q3", "Q4 high"]) if tt["income"].notna().any() else None
    out = {}

    def line_for(name, n, auc, flag):
        line = f"{name:34s} {n:>8s} {auc:9.3f}   "
        if q is not None:
            r = pd.DataFrame({"grp": q.values, "major": y[te], "flag": flag})
            rec = r[r["major"] == 1].groupby("grp", observed=True)["flag"].mean()*100
            out[name] = {"auc": round(float(auc), 3), **{g: round(float(rec.get(g, np.nan)), 1)
                                                          for g in ["Q1 low", "Q2", "Q3", "Q4 high"]}}
            line += "  ".join(f"{g.split()[0]}:{rec.get(g, np.nan):4.0f}%" for g in ["Q1 low", "Q2", "Q3", "Q4 high"])
        return line

    print(f"2024 labels kept under targeting: {len(flagged_2024)}/{in2024.sum()} "
          f"(+{len(baseline)} random baseline in arm C)\n")
    print(f"{'regime':34s} {'train_n':>8s} {'test_AUC':>9s}   recall of majors by income quartile (top 20% flagged)")
    for name, tr_idx in arms.items():
        p = fit_predict(tr_idx, te)
        print(line_for(name, f"{len(tr_idx):,}", roc_auc_score(y[te], p), mf.top_weights(p)))
    for name, col in (("ref: one-line rule (no training)", mf.BASELINES[mf.RULE]),
                      ("ref: persistence (no training)", "persistence")):
        v = d.loc[te, col].values
        print(line_for(name, "-", roc_auc_score(y[te], v), mf.top_weights(v)))
    print("\nRead: a big drop in B's Q1 (low-income) recall vs A would mean targeting is going blind")
    print("to low-signal areas, and C pulling it back would show the baseline safeguard working.")
    print("LIMIT: this is ONE round of censoring (2024 labels only) with full 2023 history kept;")
    print("real feedback compounds over many cycles, so a small effect here is reassuring, not a")
    print("clean bill of health: recall by group still has to be monitored live after deployment.")
    mf.save_results("feedback", out)


if __name__ == "__main__":
    main()
