"""Feedback-loop stress test: what happens to the model and the no-model orderings if the County
inspected only what a model flagged, round after round?

The labels, and the RECORD every feature is built from, are generated by the inspections that
are made. If a routine inspection is skipped, its label is missing AND the facility's history goes
stale: no new score, no "days since", no majors. An earlier version of this script dropped only the
labels and kept every facility's full record, and it selected purely on model features, so it
could not show this harm (and called the rule and persistence untouchable, which they are not:
they read the same record).

Here, in each quarter of 2024:
  1. a model is trained on the (censored) record so far;
  2. the quarter's routine inspections are kept only if flagged in its top KEEP share (arm B), or
     that plus a random BASELINE share of the rest (arm C); arm A keeps everything;
  3. every other routine inspection is deleted from the record, with the facility's re-inspections
     and follow-ups in the FOLLOWUP_DAYS after it (the visits it would have triggered).
Then the model, the one-line rule and persistence are rebuilt from the censored record and scored
on the real 2025+ inspections (whose labels are all observed), with recall broken out by ZIP
income group. Arm C runs over several seeds. As everywhere else, the model is trained and every
ordering scored as the monthly list would be: on features as of the 1st of each month
(model_food.month_start_rows, fit_as_deployed). The test inspections are the same in every arm (the
censoring only touches 2024), so each arm's AUC minus arm A's gets a paired 95% interval over
facilities (arm C: the mean over its seeds).

Scope: this simulates an INSPECT-LESS policy, which this project does not propose. Reordering
visits within the County's schedule removes none, so it is arm A by construction."""
import json, os
import numpy as np, pandas as pd
from sklearn.metrics import roc_auc_score
import model_food as mf
from fairness_check import zip_groups

ROUNDS = [("2024-01-01", "2024-03-31"), ("2024-04-01", "2024-06-30"),
          ("2024-07-01", "2024-09-30"), ("2024-10-01", "2024-12-31")]
KEEP, BASELINE, FOLLOWUP_DAYS, SEEDS = 0.40, 0.15, 45, (0, 1, 2)
FOLLOWUP_TYPES = ("Re-inspection", "Follow-up")   # visits a routine triggers; complaints would still happen
GROUPS = ["Q1 low", "Q2", "Q3", "Q4 high"]


def censor(raw, drop_rows):
    """Remove the routine inspections at `drop_rows` (index labels of `raw`) and each facility's
    re-inspections and follow-ups (FOLLOWUP_TYPES) in the FOLLOWUP_DAYS after one of them: the visits
    that routine would have triggered. Complaint investigations do not depend on it and stay."""
    dropped = raw.loc[drop_rows, ["business_id", "completed_date"]]
    keep = pd.Series(True, index=raw.index)
    keep[drop_rows] = False
    nr = raw[raw["insp_type"].astype(str).isin(FOLLOWUP_TYPES)].reset_index().rename(columns={"index": "_ix"})
    m = nr.merge(dropped.rename(columns={"completed_date": "_d"}), on="business_id")
    gap = (m["completed_date"] - m["_d"]).dt.days
    keep[m.loc[(gap >= 0) & (gap <= FOLLOWUP_DAYS), "_ix"].unique()] = False
    return raw[keep]


def simulate(raw, keep_share, base_share, seed):
    rng = np.random.default_rng(seed)
    rec = raw
    dropped = 0
    for start, end in ROUNDS if keep_share is not None else []:
        s, e = pd.Timestamp(start), pd.Timestamp(end)
        rf = mf.add_features(rec)
        d = mf.routine_rows(rf)
        d = d[d["completed_date"] <= e]
        ms = mf.month_start_rows(rf, d)                      # what a list made on each 1st would read
        dt_ = d["completed_date"]
        cand = ms[((dt_ >= s) & (dt_ <= e)).to_numpy()]
        p = mf.fit_as_deployed(ms, (dt_ < s).to_numpy()).predict(cand)
        keep = p >= np.quantile(p, 1 - keep_share)
        rest = np.flatnonzero(~keep)
        if base_share and len(rest):
            keep[rng.choice(rest, int(round(base_share * len(rest))), replace=False)] = True
        drop = cand.index[~keep]
        dropped += len(drop)
        rec = censor(rec, drop)
    rf = mf.add_features(rec)
    d = mf.routine_rows(rf)
    ms = mf.month_start_rows(rf, d)
    te = (d["completed_date"] > pd.Timestamp(mf.TRAIN_END)).to_numpy()
    model = mf.fit_as_deployed(ms, mf.train_mask(d, mf.HEADLINE))
    t = d[te].assign(days_since_last=ms.loc[te, "days_since_last"].values)   # as of the 1st, like the scores
    return t, {"Model": model.predict(ms[te]), "One-line rule": ms.loc[te, mf.BASELINES[mf.RULE]].values,
               "Persistence": ms.loc[te, "persistence"].values}, dropped


def paired_auc_interval(y, codes, base, others, boot=mf.BOOT):
    """95% interval of mean(AUC of each score in `others`) minus AUC of `base`, over facilities
    resampled with replacement (codes); every score is on the same rows as y."""
    def stat(w):
        return np.mean([roc_auc_score(y, o, sample_weight=w) for o in others]) - roc_auc_score(y, base, sample_weight=w)
    return mf.facility_interval(codes, stat, boot)


def main():
    raw = mf.load()
    inc = {}
    if os.path.exists("acs_cache.json"):
        with open("acs_cache.json", encoding="utf-8") as fh:
            inc = json.load(fh).get("inc", {})
    arms = {"A no censoring (= reordering only)": (None, 0.0, (0,)),
            f"B inspect only the model's top {KEEP:.0%}": (KEEP, 0.0, (0,)),
            f"C top {KEEP:.0%} + random {BASELINE:.0%} of the rest": (KEEP, BASELINE, SEEDS)}
    out, kept = {}, {}                  # kept: each arm's test rows and scores, for the paired intervals
    print(f"four quarterly rounds in 2024; unkept routine inspections and their follow-ups within "
          f"{FOLLOWUP_DAYS} days are deleted from the record; everything is rebuilt from what is left\n")
    for name, (ks, bs, seeds) in arms.items():
        runs = []
        for sd in seeds:
            t, scores, dropped = simulate(raw, ks, bs, sd)
            y = t["major"].values.astype(int)
            t = t.assign(zip5=t["zip"].astype(str).str.extract(r"(\d{5})")[0])
            t["income"] = t["zip5"].map(inc)
            grp = zip_groups(t, "income", GROUPS) if t["income"].notna().any() else pd.Series(np.nan, index=t.index)
            r = {"seed": sd, "dropped_routine": int(dropped),
                 "stale_days_since_last": round(float(t["days_since_last"].mean()), 1)}
            for a, v in scores.items():
                flag = mf.top_weights(v)
                r[a] = {"auc": round(float(roc_auc_score(y, v)), 4),
                        **{g: round(float(100 * (flag * y)[grp.values == g].sum() / max(y[grp.values == g].sum(), 1)), 1)
                           for g in GROUPS}}
            runs.append(r)
            kept.setdefault(name, []).append((t["inspection_id"].to_numpy(), y, scores))
        agg = {a: {k: round(float(np.mean([r[a][k] for r in runs])), 3 if k == "auc" else 1)
                   for k in ["auc"] + GROUPS} for a in ("Model", "One-line rule", "Persistence")}
        out[name] = {"runs": runs, "mean": agg, "dropped_routine": runs[0]["dropped_routine"]}
        print(f"{name}: {runs[0]['dropped_routine']:,} routine inspections removed; mean days since the last visit "
              f"in 2025+ {runs[0]['stale_days_since_last']:.0f}")
        for a, m in agg.items():
            print(f"    {a:14s} AUC {m['auc']:.3f}   recall of majors (top 20%) by income quartile: " +
                  "  ".join(f"{g.split()[0]} {m[g]:.0f}%" for g in GROUPS))
    # ---- each arm minus arm A, paired over facilities (the same 2025+ inspections in every arm) ----
    ids_a, y_a, sc_a = kept[next(iter(arms))][0]
    codes = pd.factorize(pd.Series(ids_a).map(dict(zip(raw["inspection_id"], raw["business_id"]))))[0]
    print("\n=== each arm minus A: AUC, paired 95% interval over facilities ===")
    for name in list(arms)[1:]:
        out[name]["minus_A"] = {}
        for a in ("Model", "One-line rule", "Persistence"):
            others = []
            for ids, y, sc in kept[name]:
                assert len(ids) == len(ids_a), "arms must score the same test inspections"
                others.append(pd.Series(sc[a], index=ids).reindex(ids_a).to_numpy())
            diff = float(np.mean([roc_auc_score(y_a, o) for o in others]) - roc_auc_score(y_a, sc_a[a]))
            ci = paired_auc_interval(y_a, codes, sc_a[a], others)
            out[name]["minus_A"][a] = {"auc": round(diff, 4), "ci": ci}
            print(f"  {name[:34]:34s} {a:14s} {diff:+.4f} [{ci[0]:+.4f}, {ci[1]:+.4f}]")

    print("\nRead: B's losses against A are what inspecting only the model's picks would cost, for the model AND for")
    print("the rules that read the same record; C shows how much a random baseline gives back. Reordering visits")
    print("within the schedule removes none (arm A). Recall by group still has to be monitored live.")
    mf.save_results("feedback", {"rounds": ROUNDS, "keep": KEEP, "baseline": BASELINE,
                                 "followup_days": FOLLOWUP_DAYS, "arms": out})


if __name__ == "__main__":
    main()
