"""Publish the City staff site: food-dashboard with the real export, to a PRIVATE GitHub repository
that Render builds and serves behind a password (city_site/server.mjs). The real export never
enters this public repository.

    python export_site.py && python publish_city_site.py      # after each refresh

    --repo OWNER/NAME   the private deploy repository (default ChenhaoZhang01/sdfood-city;
                        created, private, on the first run)
    --dir PATH          its local checkout (default ../sdfood-city, next to this repository)

On Render (once): a Node web service from that repository, build `npm ci && npx vite build`,
start `node server.mjs`, env SITE_PASSWORD (and NODE_VERSION=24, VITE_GOOGLE_MAPS_*). Each push
redeploys it."""
import argparse, json, os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SITE = ROOT / "data" / "site"


def run(cmd, cwd):
    print("$ " + " ".join(cmd), flush=True)
    return subprocess.run(cmd, cwd=cwd, check=True, text=True, capture_output=True).stdout


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--repo", default="ChenhaoZhang01/sdfood-city")
    ap.add_argument("--dir", default=str(ROOT.parent / "sdfood-city"))
    args = ap.parse_args(argv)
    meta = json.loads((SITE / "meta.json").read_text(encoding="utf-8"))
    if meta.get("sample"):
        sys.exit("data/site holds the sample; run export_site.py first")
    out = Path(args.dir)
    out.mkdir(parents=True, exist_ok=True)
    if not (out / ".git").exists():
        run(["git", "init", "-b", "main"], out)
    # Refuse to push the real export anywhere public.
    remote = subprocess.run(["git", "remote", "get-url", "origin"], cwd=out, capture_output=True, text=True).stdout.strip()
    if not remote:
        exists = subprocess.run(["gh", "repo", "view", args.repo], capture_output=True).returncode == 0
        if not exists:
            run(["gh", "repo", "create", args.repo, "--private"], out)
        run(["git", "remote", "add", "origin", f"https://github.com/{args.repo}.git"], out)
        remote = args.repo
    vis = run(["gh", "repo", "view", args.repo, "--json", "visibility", "--jq", ".visibility"], out).strip()
    if vis != "PRIVATE":
        sys.exit(f"{args.repo} is {vis}: the real export only goes to a private repository")

    for p in out.iterdir():                                   # a clean copy each time, keeping .git
        if p.name == ".git":
            continue
        if p.is_dir():                                        # OneDrive may hold an emptied folder: leave it
            shutil.rmtree(p, onexc=lambda fn, path, exc: None if fn is os.rmdir else (_ for _ in ()).throw(exc))
        else:
            p.unlink()
    for rel in run(["git", "ls-files", "--cached", "--others", "--exclude-standard", "food-dashboard"], ROOT).splitlines():
        rel = Path(rel).relative_to("food-dashboard")
        if rel.parts[:2] == ("public", "data"):
            continue
        (out / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / "food-dashboard" / rel, out / rel)
    data = out / "public" / "data"
    data.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SITE / "facilities.geojson", data / "facilities.geojson")
    shutil.copy2(SITE / "meta.json", data / "meta.json")
    shutil.copytree(SITE / "place", data / "place", dirs_exist_ok=True)
    shutil.copy2(ROOT / "city_site" / "server.mjs", out / "server.mjs")
    (out / "README.md").write_text(
        "# San Diego Food Inspection Record: City staff site\n\nPRIVATE. Generated by publish_city_site.py in "
        "the sdfood repository; do not edit here. Holds the real export: never make this repository public.\n",
        encoding="utf-8")

    run(["git", "add", "-A"], out)
    if subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=out).returncode == 0:
        print("nothing changed")
        return 0
    run(["git", "commit", "-q", "-m", f"City site: {meta['run']}, inspections through {meta['inspections_through']}"], out)
    run(["git", "push", "-q", "-u", "origin", "main"], out)
    print(f"pushed {meta['run']} ({meta['places']} places) to {args.repo}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
