"""How much the students' point rule leans on reading a closure as 70.

A routine inspection that ended in a health closure order usually has no County score; the rule
reads it as CLOSURE_SCORE (70). This runs the average-score rule's backtest with that reading set to
70, 80, 90 and the County's own point formula on the items cited that day (100 less 4 per major, 2
per minor, 1 per good-retail item), at the same three City origins the export uses, and reports for
each: AUC among eligible restaurants, band 1's rate at the frozen cut and at the same share of the
list, and how many band-1 places are there only because of a closure.

    python tools/closure_sensitivity.py                  # prints the table; --out docs/CLOSURE_SENSITIVITY.md

The decision rule, fixed before running it: keep 70 unless another reading beats it by more than
EPSILON (0.01) AUC at every origin, the same tolerance the rule itself was chosen by. Aggregates
only; no business is named.
"""
import argparse, json, sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import export_site as es  # noqa: E402

READINGS = (70, 80, 90, "county")


def evaluate(places, origins, cut, shares):
    rows = []
    for T in origins:
        pts, pos, lab, elig, _ = es.area_origin(places, T, "city_bands", es.AVERAGE_RULE, {})
        m = lab & elig
        top = pts >= cut
        order = np.argsort(-pts[elig], kind="stable")
        row = {"as_of": T, "auc": es.auc(pos[m], pts[m]), "labelled": int(m.sum()),
               "band_1": {"labelled": int((m & top).sum()), "rate": _rate(pos, m & top)}, "same_share": {}}
        for share in shares:
            k = max(1, int(round(share * elig.sum())))
            by_share = np.zeros(len(pts), bool)
            by_share[np.flatnonzero(elig)[order[:k]]] = True
            row["same_share"][f"{share:.4f}"] = {"labelled": int((m & by_share).sum()), "rate": _rate(pos, m & by_share)}
        rows.append(row)
    return rows


def _rate(pos, mask):
    n = int(mask.sum())
    return round(float(pos[mask].sum()) / n, 4) if n else None


def closure_carried(places, T, cut):
    """Band-1 places (at the cut) that would be below it without their closures, and all band-1 places."""
    te = es.frame(places, [T], scope="city_bands", labelled=False, cache={})
    pts = es.AVERAGE_RULE.score(te.F)
    elig = np.array([es.eligible(f) for f in te.feats])
    n = carried = 0
    for j in np.flatnonzero(elig & (pts >= cut)):
        i, t = te.idx[j]
        used = es.scores_used(places[i], t)
        rest = [u["score"] for u in used if not u["closure"]]
        n += 1
        if any(u["closure"] for u in used) and (not rest or 100 - np.floor(np.mean(rest) + 0.5) < cut):
            carried += 1
    return carried, n


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--pull", type=Path, default=es.RAW)
    ap.add_argument("--rule", type=Path, default=es.FROZEN, help="the frozen rule, for its cut (default docs/rule.json)")
    ap.add_argument("--out", type=Path, help="write the table as Markdown here")
    ap.add_argument("--share", type=float, action="append",
                    help="compare the top SHARE of the list under each reading (repeatable; default 0.025 and band 1's share)")
    args = ap.parse_args(argv)
    raw = es.read_pull(args.pull)
    frozen = es._json(args.rule, None)
    cut = frozen["cuts"][0] if frozen and frozen.get("cuts") else 8.0
    b1_share = frozen["card"]["rows"][0]["share"] if frozen and frozen["card"]["rows"] else None
    shares = args.share or [0.025] + ([b1_share] if b1_share else [])
    results = {}
    for reading in READINGS:
        es.CLOSURE_VALUE = None if reading == es.CLOSURE_SCORE else reading
        places, _, _ = es.prepare(raw, es.load_districts())
        _, _, validate, confirm = es.origin_dates(places)
        origins = validate + [confirm]
        results[str(reading)] = {"origins": evaluate(places, origins, cut, shares),
                                 "carried_by_closure": closure_carried(places, confirm, cut)}
        print(f"{reading}: " + ", ".join(f"{r['as_of']} AUC {r['auc']:.3f}" for r in results[str(reading)]["origins"]), flush=True)
    es.CLOSURE_VALUE = None
    base = results[str(es.CLOSURE_SCORE)]["origins"]
    better = [k for k, v in results.items() if k != str(es.CLOSURE_SCORE)
              and all(o["auc"] - b["auc"] > es.EPSILON for o, b in zip(v["origins"], base))]
    verdict = (f"keep {es.CLOSURE_SCORE}: no other reading beats it by more than {es.EPSILON} AUC at every origin"
               if not better else f"change the reading: {', '.join(better)} beat {es.CLOSURE_SCORE} by more than "
               f"{es.EPSILON} AUC at every origin (refit with export_site.py --refit)")
    L = ["# How much the rule leans on reading a closure as 70", "",
         f"Generated by `tools/closure_sensitivity.py` from the pull finished "
         f"{(es._json(es.pull_meta_for(args.pull) or es.PULL, {}) or {}).get('finished', 'on an unknown date')}. "
         f"Band 1 is {int(cut)}+ points (the frozen cut). \"Top X%\" is that share of eligible City restaurants under each "
         "reading, so a reading that only moves places across the cut is compared fairly "
         f"(shares: {', '.join(f'{x:.1%}' for x in shares)}; rerun with the same --share values to reproduce).", "",
         "| a closure reads as | origin | AUC, eligible | labelled | band 1 rate (n) | "
         + " | ".join(f"top {x:.1%} rate (n)" for x in shares) + " |", "|---|---|---|---|---|" + "---|" * len(shares)]
    for k, v in results.items():
        name = "the County's point formula" if k == "county" else k
        for o in v["origins"]:
            L.append(f"| {name} | {o['as_of']} | {o['auc']:.3f} | {o['labelled']} | {es._fmt(o['band_1']['rate'])} ({o['band_1']['labelled']}) | "
                     + " | ".join(f"{es._fmt(v_['rate'])} ({v_['labelled']})" for v_ in o["same_share"].values()) + " |")
    L += ["", "| a closure reads as | band 1 places at the confirmation origin only because of a closure |", "|---|---|"]
    for k, v in results.items():
        c, n = v["carried_by_closure"]
        L.append(f"| {'the County point formula' if k == 'county' else k} | {c} of {n} |")
    L += ["", f"Decision rule, fixed in advance: keep {es.CLOSURE_SCORE} unless another reading beats it by more than "
          f"{es.EPSILON} AUC at every origin. Result: **{verdict}**.", ""]
    text = "\n".join(L)
    print(text)
    if args.out:
        args.out.write_text(text, encoding="utf-8")
        (args.out.with_suffix(".json")).write_text(json.dumps({"cut": cut, "shares": shares, "results": results, "verdict": verdict},
                                                              indent=1), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
