"""A coarse screen by restaurant name: are clean restaurants whose names suggest some cuisines put in
band 1 more often than others?

Not a validated measure of anything about the owners: a keyword list on the business name, which
suggests a cuisine at best. At the backtest's confirmation origin, among eligible City restaurants
whose next routine inspection found no major violation (the ones band 1 would name wrongly), it
reports the share in band 1 (the frozen cut) by name group, and each group's share over the share
for names the lists do not classify, with an address-cluster bootstrap interval. Aggregates only:
no business is named, and nothing is written with a name in it.

    python tools/name_screen.py --out docs/NAME_SCREEN.md
"""
import argparse, json, re, sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import export_site as es  # noqa: E402

# Whole words in the business name, lower case. Generic words only.
GROUPS = {
    "East or Southeast Asian": ["pho", "thai", "sushi", "ramen", "wok", "dim", "sum", "szechuan", "sichuan", "hunan", "mandarin",
                                "chinese", "china", "panda", "dragon", "boba", "teriyaki", "korean", "bbq", "tofu", "noodle",
                                "noodles", "banh", "mi", "viet", "vietnamese", "saigon", "pho", "bento", "izakaya", "katsu",
                                "poke", "hibachi", "tokyo", "seoul", "bangkok", "manila", "filipino", "lumpia", "curry"],
    "Latin or Mexican": ["taco", "tacos", "taqueria", "mariscos", "cocina", "tortas", "torta", "pupusa", "pupuseria", "burrito",
                         "burritos", "cantina", "mexican", "mexicana", "el", "la", "los", "las", "carniceria", "panaderia",
                         "birria", "tamales", "salvadoreno", "peruvian", "cuban", "latin"],
}
WORD = re.compile(r"[a-z]+")


def group_of(name):
    words = set(WORD.findall((name or "").lower()))
    for g, keys in GROUPS.items():
        if words & set(keys):
            return g
    return "unclassified"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--pull", type=Path, default=es.RAW)
    ap.add_argument("--rule", type=Path, default=es.FROZEN)
    ap.add_argument("--boot", type=int, default=2000)
    ap.add_argument("--out", type=Path)
    a = ap.parse_args(argv)
    frozen = es._json(a.rule, None)
    cut = frozen["cuts"][0] if frozen and frozen.get("cuts") else 8.0
    places, _, _ = es.prepare(es.read_pull(a.pull), es.load_districts())
    _, _, _, confirm = es.origin_dates(places)
    pts, pos, lab, elig, cl, te, _, _ = es.area_origin(places, confirm, "city_bands", es.AVERAGE_RULE, {}, detail=True)
    clean = elig & lab & (pos == 0)
    groups = np.array([group_of(places[i]["name"]) for i, _ in te.idx])
    in_b1 = pts >= cut
    rows = {}
    base_mask = clean & (groups == "unclassified")
    base = in_b1[base_mask].mean() if base_mask.any() else None
    for g in list(GROUPS) + ["unclassified"]:
        m = clean & (groups == g)
        rows[g] = {"clean_places": int(m.sum()), "in_band_1": int((m & in_b1).sum()),
                   "share": round(float(in_b1[m].mean()), 4) if m.any() else None}
    draws = {g: [] for g in GROUPS}
    for pick in es._cluster_draws(cl, a.boot, es.SEED):
        c, gp, b = clean[pick], groups[pick], in_b1[pick]
        bm = c & (gp == "unclassified")
        if not bm.any() or not b[bm].mean():
            continue
        for g in GROUPS:
            m = c & (gp == g)
            if m.any():
                draws[g].append(b[m].mean() / b[bm].mean())
    for g in GROUPS:
        rows[g]["ratio_to_unclassified"] = round(rows[g]["share"] / base, 2) if base and rows[g]["share"] is not None else None
        rows[g]["interval"] = ([round(float(np.percentile(draws[g], 2.5)), 2), round(float(np.percentile(draws[g], 97.5)), 2)]
                               if draws[g] else None)
    L = ["# A coarse screen by restaurant name", "",
         "Generated by `tools/name_screen.py`. A keyword list on the business name, which suggests a cuisine at best: not the "
         "owner's ethnicity, and not a validated measure. Among eligible City restaurants whose next routine inspection after "
         f"{confirm} found no major violation, the share the rule puts in band 1 ({int(cut)}+ points), by name group. The rule "
         "is the County's own average score, so it passes any gap in those scores through unchanged; it may reflect real "
         "differences, or how items are cited, which the record cannot separate (it has no inspector ids).", "",
         "| name group | clean restaurants | in band 1 | share | over unclassified | 95% interval |", "|---|---|---|---|---|---|"]
    for g, r in rows.items():
        L.append(f"| {g} | {r['clean_places']} | {r['in_band_1']} | {es._fmt(r['share'])} | "
                 f"{r.get('ratio_to_unclassified', '') or ''} | {r.get('interval', '') or ''} |")
    text = "\n".join(L) + "\n"
    print(text)
    if a.out:
        a.out.write_text(text, encoding="utf-8")
        a.out.with_suffix(".json").write_text(json.dumps({"cut": cut, "confirm": confirm, "groups": rows}, indent=1), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
